=== BenjaminHerbert/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="usergroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="nonEmptyString">
                    <xs:annotation>
                        <xs:documentation>Vollständiger Name der Usergroup in Langfassung,
                            z.B. Python UserGroup RheinMain
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="nickname" type="nonEmptyString" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="description" type="nonEmptyString">
                    <xs:annotation>
                        <xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
                            ausführlich sein.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="url" type="xs:anyURI">
                    <xs:annotation>
                        <xs:documentation>Die URL der Homepage der Usergroup.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="tags">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tag" type="xs:token" maxOccurs="3"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mailinglist" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="url" type="xs:anyURI"/>
                                        <xs:element name="label" type="nonEmptyString"/>
                                        <xs:element name="description" type="nonEmptyString" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" minOccurs="0" type="email"/>
                            <xs:element name="twitter" minOccurs="0" type="twitter"/>
                            <xs:element name="hashtag" minOccurs="0" type="hashtag"/>
                            <xs:element name="facebook" minOccurs="0" type="facebook"/>
                            <xs:element name="googleplus" minOccurs="0" type="googleplus"/>
                            <xs:element name="xing" minOccurs="0" type="xing"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="defaultmeetinglocation" type="location" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Dieses Element beschreibt die den Ort, an dem sich die Usergroup normalerweise
                            trifft. Kann durch die Information einzelnen Meetings überschrieben werden. Bei iCal
                            überschreibt die defaultlocation immer die Angabe aus dem iCal-Feed.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="schedule" minOccurs="0">
                    <xs:complexType>
                        <xs:annotation>
                            <xs:documentation>Liefert Information zu den nächsten Treffen der
                                UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
                                werden, oder die Meetings werden manuell konfiguriert.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:choice>
                            <xs:element name="ical" type="xs:anyURI"/>
                            <xs:element name="meeting" maxOccurs="unbounded" type="meeting"/>
                        </xs:choice>
                        <xs:attribute name="usedefaultmeetinglocation" type="xs:boolean"
                                      default="false" use="optional">
                            <xs:annotation>
                                <xs:documentation>Gibt an, ob für die Ortsangabe die Angaben aus
                                    ../defaultmeetinglocation verwendet werden sollen (wenn
                                    vorhanden).
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sponsors" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sponsor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="nonEmptyString"/>
                                        <xs:element name="url" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="photocredits" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="logo" type="nonEmptyString" minOccurs="0"/>
                            <xs:element name="group" type="nonEmptyString" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="email">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für E-Mail Adressen
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="twitter">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Twitter-Handles
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="@[a-zA-Z0-9_]{1,15}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="hashtag">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Hashtags
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="#[a-zA-Z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="facebook">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf facebook.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.facebook\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="xing">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf xing.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.xing\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="googleplus">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf Google+
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://plus\.google\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nonEmptyString">
        <xs:annotation>
            <xs:documentation>Ein nicht-leerer String</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="meeting">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Meetings (zukünftige
                und vergangene)
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="time" type="xs:dateTime"/>
            <xs:element name="name" type="nonEmptyString"/>
            <xs:element name="description" type="nonEmptyString" minOccurs="0"/>
            <xs:element name="url" type="xs:anyURI" minOccurs="0"/>
            <xs:element name="location" type="location" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="plz">
        <xs:annotation>
            <xs:documentation>Eine deutsche PLZ</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="10000"/>
            <xs:maxInclusive value="99999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="location">
        <xs:sequence>
            <xs:element name="name" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. OFfenraum Coworking Space
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. OFfenraum ist ein Coworking Space im
                        Rhein-Main-Gebiet südlich von Frankfurt in Offenbach am Main,
                        in der Nähe des Hauptbahnhofs, Hassia Fabrik und
                        Stadtkrankenhaus.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="url" type="xs:anyURI" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. http://offenraum.de/#lage
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="twitter" type="twitter" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. @OFfenraum
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="publictransport" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Regionalbahn HBf Offenbach. S1, S2, S8,
                        S9 Offenbach Markplatz. Bus 104 Haydnstraße.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="street" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. Senefelderstr. 63</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="zip" type="plz">
                <xs:annotation>
                    <xs:documentation>z.B. 63069</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="city" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. Offenbach</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="region" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Hessen</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="country" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Deutschland</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BenjaminHerbert/ugrm-data/usergroup/ffmcloud.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Cloud Frankfurt</name>
    <description>The Frankfurt Cloud provides an infrastructure tool to support research in the appropriate application
        of clouds with regard to different user profiles, e.g. data intensive applications, compute intensive
        applications, communication intensive applications, intrinsically parallel application structures, and
        intrinsically sequential application structures. Moreover, the Frankfurt Cloud is a testbed to evaluate cloud
        products and service offerings of the market and to design and investigate novel cloud management concepts, e.
        g. load distribution, billing the users, and management of federated clouds. Our long-term goal is to contribute
        to a "cloud management technology" which also comprises questions like outsourcing and service componentization.
    </description>
    <url>http://www.frankfurt-cloud.com/</url>
    <tags>
        <tag>Cloud</tag>
    </tags>
    <photocredits>
        <group>Foto: Unbekannt. Entnommen von [frankfurt-cloud.com](http://www.frankfurt-cloud.com/about-us/).</group>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/frontend.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Frontend-Meetup Wiesbaden</name>
    <description>Beim Frontend-Meetup Wiesbaden geht es um Frontend-Kernthemen gehen wie HTML(5), CSS(3),
        OOCSS-/BEM-Patterns, SASS, Webstandards, Responsive Design, Accessibility, Arbeitsweisen, Kommunikation,
        Styleguides, Deployment etc pp. …
    </description>
    <url>http://usergroup.rheinmainrocks.de/~frontend</url>
    <tags>
        <tag>Frontend</tag>
        <tag>Webstandards</tag>
        <tag>Webdesign</tag>
    </tags>
    <defaultmeetinglocation>
        <name>AOE GmbH</name>
        <publictransport>Die Adresse kann sehr gut mit Bussen ab dem Wiesbadener Hbf erreicht werden. Die Bus Linien
            15,16 und 28 halten fast vor dem Büro.
        </publictransport>
        <street>Borsigstr. 3</street>
        <zip>65205</zip>
        <city>Wiesbaden</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2014-02-25T19:00:00+01:00</time>
            <name>1. Frontend-Meetup in Wiesbaden</name>
            <description>
                **Agenda**

                * Marc Dix wird uns “DalekJS – automatisiertes Frontend-Testing mit Javascript” vorstellen,
                * Jens Grochtdreis zeigt uns “Praktische SASS-Tipps“
                * und Jan Deppisch erzählt, was ihm über dieses Meetup hinaus noch vorschwebt.
                * schnitzel.html: Danach können wir den Abend noch gemütlich im Schnitzel’s nebenan ausklingen lassen.

                Der Eintritt ist natürlich frei.
            </description>
            <url>http://netzartist.de/blog/2014/02/frontend-meetup-in-wiesbaden/</url>
        </meeting>
    </schedule>
    <team>
        <person>
            <name>Jan Deppisch</name>
            <url>http://netzartist.de/</url>
            <email>mail@netzartist.de</email>
            <twitter>@netzartist</twitter>
        </person>
    </team>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/idugrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>InDesign User Group Rhein/Main</name>
    <nickname>IDUGRM</nickname>
    <description>Die Indesign User Group RheinMain, kurz IDUG RheinMain, ist eine seit Februar 2011 bestehende und
        ständig wachsende Community, die sich gerne und am liebsten in lockerer Atmosphäre mit InDesign und allen
        spannenden Themen rund um die Publishing-Szene beschäftigt.

        Mindestens 4-5 Mal im Jahr finden kostenlos Veranstaltungen von Anwendern für Anwender in ausgesuchten und
        wechselnden Locations statt. Wir bieten interessante Fachvorträge auf stets hohem Niveau. Die Referenten kommen
        aus den eigenen Reihen, Firmen oder Organisationen.

        Es gibt jedes mal eine Verlosung mit wertvollen Preisen, etwas für den Gaumen und jede Menge netter Leute, mit
        denen man sich in der Pause oder auch anschließend beim get-together austauschen kann.
    </description>
    <url>http://www.idug-rm.de/</url>
    <tags>
        <tag>InDesign</tag>
    </tags>
    <contact>
        <twitter>@idugrheinmain</twitter>
        <facebook>http://www.facebook.com/idugrm</facebook>
    </contact>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/vaadin.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Vaadin Frankfurt</name>
    <description>Building awesome web apps in Java? Using Vaadin or GWT? Let's share thoughts on Vaadin, GWT and web app
        development. Meetings are filled with presentations and debate on where these technologies are going, what can
        be done with them and what would be the best practices for using them.
    </description>
    <url>http://www.meetup.com/Vaadin-Frankfurt/</url>
    <tags>
        <tag>Vaadin</tag>
        <tag>Java</tag>
        <tag>GWT</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2013-12-17T17:30:00+01:00</time>
            <name>Vaadin Frankfurt - First meetup</name>
            <description>Lets have the first Vaadin meet-up at the same evening we are having the GWT.create venue.
                After the meet-up everyone is free to join the GWT.create venue for networking and fun without any
                payments or tickets whatsoever.

                Please share your thoughts on what you wish to hear or discuss during the meet-up. We'll also gather
                practical ideas for 2014. Lets have this really casual and easy-going. And do note, there are a lot of
                Vaadin and GWT superstars present in the conference so we have the possibility to have really deep
                face-to-face discussions too if needed.
            </description>
            <url>http://www.meetup.com/Vaadin-Frankfurt/events/150480172/</url>
            <location>
                <name>Radisson Blu Frankfurt</name>
                <street>Franklin Str 65</street>
                <zip>60486</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <logo>Logo: [Ville Ingman](http://www.meetup.com/Vaadin-Frankfurt/photos/17949332/294903522/#294903522)</logo>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/graphdbffm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Graph DB Frankfurt</name>
    <description>Entwickler mit Interesse an Graph-Datenbanken, oder solche, die bereits mit Graph-Datenbanken arbeiten,
        um soziale, geografische, hierarchische oder anderweitig hochgradig verknüpfte Daten zu verarbeiten.

        Wir hosten praktische "Hands-on"-Sessions, diskutieren und beurteilen technische Lösungen, veranstalten
        Themen-Vorträge, und natürlich kommt auch das Soziale nicht zu kurz, wenn wir beim gemeinsamen Bier unsere Köpfe
        zusammenstecken.

        Seid Ihr neugierig, was Graph-Datenbanken sind, und wollt Ihr Eure Fähigkeiten und Kenntnisse außerhalb von
        relationalen Datenbanken erweitern? Dann seid Ihr hier richtig und solltet Euch uns anschließen!
    </description>
    <url>http://www.meetup.com/graphdb-frankfurt/</url>
    <tags>
        <tag>GraphDB</tag>
        <tag>Neo4J</tag>
    </tags>
    <defaultmeetinglocation>
        <name>K1 Business Club</name>
        <url>http://www.k1bc.de/</url>
        <foursquare>https://de.foursquare.com/v/k1-businessclub-gmbh/4dc1ac2552b1877d85b9a17e</foursquare>
        <twitter>@k1bc</twitter>
        <street>Hanauer Landstraße 204</street>
        <zip>60314</zip>
        <city>Frankfurt</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2013-05-16T09:00:00+02:00</time>
            <name>Neo4j Tutorial - Frankfurt</name>
            <description>Dieser Neo4j Workshop führt in die Funktionsweise und Nutzung der Neo4j Graphendatenbank ein.
                Durch eine Mischung aus Theorie und praktischen Übungen können die Teilnehmer schnell erlernen, wie
                einfach es ist, eine auf Neo4j basierende Applikation zu erstellen.
            </description>
            <url>http://www.meetup.com/graphdb-frankfurt/events/118706232/</url>
        </meeting>
        <meeting>
            <time>2013-05-16T19:00:00+02:00</time>
            <name>Let's spread some graph love :-)</name>
        </meeting>
    </schedule>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/lugffm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Linux User Group Frankfurt</name>
    <nickname>LUGFFM</nickname>
    <description>Unsere Gruppe existiert seit 1998. Zum "harten Kern" der Gruppe gehören etwa 50 Nutzer, die im
        Rhein-Main-Gebiet leben oder/und arbeiten, wovon regelmässig 15-30 Mitglieder zum Stammtisch an unserem
        Montagsterminen kommen, wobei unsere Vortäge am Dienstagstermin bisweilen von bis zu 60 und mehr Teilnehmern
        besucht werden. Bei uns sind alle Linux-Distributionen vertreten und gerne gesehen.
    </description>
    <url>http://www.lug-frankfurt.de/</url>
    <tags>
        <tag>Linux</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>http://www.lug-frankfurt.de/MailingListe</url>
            <label>Mailingliste</label>
            <description>Zwischen den Treffen diskutieren wir in unserer Mailingliste, an der jede/r Interesssierte/r
                teilnehmen kann.
            </description>
        </mailinglist>
    </contact>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/rheinmainjs.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>JavaScript User Group für Wiesbaden und Rhein-Main</name>
    <nickname>RheinMainJS</nickname>
    <description>RheinMainJS ist eine User Group zum Thema JavaScript und angrenzende Gebiete wie mobile Entwicklung.
        Wir treffen uns zurzeit in unregelmäßigen Abständen in Wiesbaden. Die Teilnahme steht dabei offen und ist
        kostenlos. Bei jedem Treffen werden in der Regel zwei Vorträge mit anschließender Diskussion gehalten.
    </description>
    <url>http://rheinmainjs.de/</url>
    <tags>
        <tag>Javascript</tag>
    </tags>
    <contact>
        <googleplus>https://plus.google.com/113716277582361446417/</googleplus>
    </contact>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/cccda.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Chaos Darmstadt</name>
    <description>Chaos Darmstadt ist die örtliche Vertretung des Chaos in Darmstadt. Wir sind "ErfA"-Kreis des CCC und
        eine Hochschulgruppe der TU Darmstadt. (Bei uns sind aber natürlich auch nicht studierende Personen herzlich
        willkommen!) Im Rhein-Main-Gebiet fördern wir den Zusammenhalt und Erfahrungsaustausch der Computer- und
        Chaostreffs (MetaRheinMain). Wir treffen uns jeden Dienstag um 20:00 CEST in unserem Hackerspace - der
        Trollhöhle - in der Wilhelm-Leuschner-Straße 36 in Darmstadt. Für Anfahrtsbeschreibungen frage bitte den
        Routingdienstleister deines geringsten Misstrauens. Falls du unsicher bist, ob der Raum offen ist: Ruf' an.
        Unsere Rufnummer ist 06151 627 4854. Dann die '5' wählen; wenn sich jemand meldet, ist die Wahrscheinlichkeit
        hoch, daß jemand im Hackerspace ist.
    </description>
    <url>http://chaos-darmstadt.de/</url>
    <tags>
        <tag>Computer</tag>
        <tag>CCC</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>https://lists.metarheinmain.de/mailman/listinfo/darmstadt</url>
            <label>Die große Liste, offen für alle.</label>
        </mailinglist>
        <twitter>@chaosdarmstadt</twitter>
    </contact>
</usergroup>
