=== BenjaminHerbert/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="usergroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="nonEmptyString">
                    <xs:annotation>
                        <xs:documentation>Vollständiger Name der Usergroup in Langfassung,
                            z.B. Python UserGroup RheinMain
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="nickname" type="nonEmptyString" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="description" type="nonEmptyString">
                    <xs:annotation>
                        <xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
                            ausführlich sein.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="url" type="xs:anyURI">
                    <xs:annotation>
                        <xs:documentation>Die URL der Homepage der Usergroup.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="tags">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tag" type="xs:token" maxOccurs="3"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mailinglist" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="url" type="xs:anyURI"/>
                                        <xs:element name="label" type="nonEmptyString"/>
                                        <xs:element name="description" type="nonEmptyString" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" minOccurs="0" type="email"/>
                            <xs:element name="twitter" minOccurs="0" type="twitter"/>
                            <xs:element name="hashtag" minOccurs="0" type="hashtag"/>
                            <xs:element name="facebook" minOccurs="0" type="facebook"/>
                            <xs:element name="googleplus" minOccurs="0" type="googleplus"/>
                            <xs:element name="xing" minOccurs="0" type="xing"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="defaultmeetinglocation" type="location" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Dieses Element beschreibt die den Ort, an dem sich die Usergroup normalerweise
                            trifft. Kann durch die Information einzelnen Meetings überschrieben werden. Bei iCal
                            überschreibt die defaultlocation immer die Angabe aus dem iCal-Feed.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="schedule" minOccurs="0">
                    <xs:complexType>
                        <xs:annotation>
                            <xs:documentation>Liefert Information zu den nächsten Treffen der
                                UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
                                werden, oder die Meetings werden manuell konfiguriert.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:choice>
                            <xs:element name="ical" type="xs:anyURI"/>
                            <xs:element name="meeting" maxOccurs="unbounded" type="meeting"/>
                        </xs:choice>
                        <xs:attribute name="usedefaultmeetinglocation" type="xs:boolean"
                                      default="false" use="optional">
                            <xs:annotation>
                                <xs:documentation>Gibt an, ob für die Ortsangabe die Angaben aus
                                    ../defaultmeetinglocation verwendet werden sollen (wenn
                                    vorhanden).
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sponsors" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sponsor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="nonEmptyString"/>
                                        <xs:element name="url" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="photocredits" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="logo" type="nonEmptyString" minOccurs="0"/>
                            <xs:element name="group" type="nonEmptyString" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="email">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für E-Mail Adressen
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="twitter">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Twitter-Handles
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="@[a-zA-Z0-9_]{1,15}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="hashtag">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Hashtags
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="#[a-zA-Z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="facebook">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf facebook.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.facebook\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="xing">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf xing.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.xing\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="googleplus">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf Google+
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://plus\.google\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nonEmptyString">
        <xs:annotation>
            <xs:documentation>Ein nicht-leerer String</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="meeting">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Meetings (zukünftige
                und vergangene)
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="time" type="xs:dateTime"/>
            <xs:element name="name" type="nonEmptyString"/>
            <xs:element name="description" type="nonEmptyString" minOccurs="0"/>
            <xs:element name="url" type="xs:anyURI" minOccurs="0"/>
            <xs:element name="location" type="location" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="plz">
        <xs:annotation>
            <xs:documentation>Eine deutsche PLZ</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="10000"/>
            <xs:maxInclusive value="99999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="location">
        <xs:sequence>
            <xs:element name="name" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. OFfenraum Coworking Space
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. OFfenraum ist ein Coworking Space im
                        Rhein-Main-Gebiet südlich von Frankfurt in Offenbach am Main,
                        in der Nähe des Hauptbahnhofs, Hassia Fabrik und
                        Stadtkrankenhaus.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="url" type="xs:anyURI" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. http://offenraum.de/#lage
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="twitter" type="twitter" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. @OFfenraum
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="publictransport" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Regionalbahn HBf Offenbach. S1, S2, S8,
                        S9 Offenbach Markplatz. Bus 104 Haydnstraße.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="street" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. Senefelderstr. 63</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="zip" type="plz">
                <xs:annotation>
                    <xs:documentation>z.B. 63069</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="city" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. Offenbach</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="region" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Hessen</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="country" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Deutschland</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BenjaminHerbert/ugrm-data/usergroup/donnerstalk.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Donnerstalk im Heimathafen Wiesbaden</name>
    <description>
        Der Donnerstalk ist ein angeregter Austausch zwischen sympathischen Leuten aus der Region in entspannter
        Atmosphäre, bei dem Wissenstransfer und Networking auf gelungene Weise kombiniert werden.
    </description>
    <url>http://heimathafen-wiesbaden.de/category/donnerstalk/</url>
    <tags>
        <tag>Talk</tag>
        <tag>Idea</tag>
        <tag>Beer</tag>
    </tags>
    <contact>
        <hashtag>#donnerstalk</hashtag>
    </contact>
    <defaultmeetinglocation>
        <name>heimathafen Wiesbaden</name>
        <description>Der heimathafen Wiesbaden ist ein Coworking Space &amp; Café. Wir vermieten Arbeitsplätze an
            Kreative &amp; Selbständige, Konferenzräume an Firmen &amp; Agenturen - und verkaufen Kaffee an jedermann.
        </description>
        <url>http://heimathafen-wiesbaden.de/</url>
        <foursquare>https://de.foursquare.com/heimathafenwi</foursquare>
        <twitter>@heimathafenWI</twitter>
        <publictransport>Hauptbahnhof Wiesbaden</publictransport>
        <street>Karlstraße 22 (Adelheidstraße)</street>
        <zip>65185</zip>
        <city>Wiesbaden</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2013-10-02T18:30:00+02:00</time>
            <name>Mittwochs-Donnerstalk zum Thema BIG DATA</name>
            <description>Snowden, NSA, Prism – die große Datensammelwut ist längst Realität. Doch: Hat sie auch ihr
                Gutes? Wie kann BIG DATA uns helfen, unsere Produkte, User Experience und Services besser zu machen?
                Und: Was genau meint BIG DATA eigentlich? Um diese und andere Fragen dreht sich der Donnerstalk im
                Oktober – diesmal mit einem absoluten Novum: Donnerstalk ist das erste Mal an einem Mittwoch – immerhin
                wollen wir alle am 03.10. frei haben (dem Tag der deutschen Einheit, an dem unser Café geöffnet sein
                wird). Der Vortrag lautet: BIG DATA: Zaubertrank für Staaten &amp; Unternehmen, Teufelszeug für Bürger &amp;
                Kunden?

                Infos und Anmeldung, wie immer, unter http://facebook.com/heimathafenwiesbaden/events
            </description>
            <url>http://heimathafen-wiesbaden.de/2013/09/30/premiere-mittwochs-donnerstalk-zum-thema-big-data-am-02-10/</url>
        </meeting>
        <meeting>
            <time>2013-09-05T18:30:00+02:00</time>
            <name>Donnerstalk im September: „Entfalte dein (kreatives) Potential!“</name>
            <description>Welches sind die größten Kreativitätskiller und wann schlagen diese in der Regel zu? Wie viel
                von unserem (kreativen) Potential leben wir überhaupt aus? Und wie sehr entfalten sich eigentlich
                „Kreative“ – oder gibt’s da auch noch Luft nach oben? Der Impulsvortrag hat nicht nur Antworten und Mut
                machen auf Lager. Neben einem ordentlichen Perspektivwechsel wird kräftig reflektiert, um am Ende sagen
                zu können, „Wow, da steckt wohl auch in mir noch viel mehr, als mir vermeintlich bewusst ist…! Denk- und
                Umdenkanstöße inklusive.
            </description>
            <url>https://www.xing.com/events/donnerstalk-september-entfalte-kreatives-potential-1281242</url>
        </meeting>
        <meeting>
            <time>2013-08-01T18:30:00+02:00</time>
            <name>Donnerstalk plus 1 Jahr heimathafen-Feier am 01. August</name>
            <description>
                Das Thema im August: "Design (your) Thinking"
                Design Thinking ist eine Art Kreativ-Methode, mit der sich innerhalb kurzer Zeit kreative Ideen &amp;
                innovative Lösungen entwickeln lassen. Wir lernen den strukturierten, interdisziplinären Prozess des
                Design Thinking kennen &amp; wenden ihn im konkreten Fall an. Mehr Kreativität? Mehr Innovation? Design
                (your) Thinking!

                Für den Donnerstalk ist die Anmeldung über XING ist notwendig.
            </description>
            <url>https://www.xing.com/events/donnerstalkplus-design-your-thinking-1-heimathafen-feier-1279534</url>
        </meeting>
    </schedule>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/auge.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Computer-Stammtisch der RG 600 - Frankfurt/Rhein-Main</name>
    <nickname>RG 600</nickname>
    <description>Der AUGE e.V. wurde bereits im Jahre 1979 als "Apple User Group Europe" (A.U.G.E.) gegründet und ist
        damit der wohl älteste überregionale, private und unabhängige Computerclub in Deutschland! Darüberhinaus hat der
        Verein auch im deutschsprachigen Ausland Freunde gefunden, einige Mitglieder sind in der Schweiz, in Österreich
        und auf der ganzen Welt zu finden. Der Vereinsname geht noch immer auf die ursprüngliche Abkürzung zurück, auch
        wenn heute natürlich Anwender sämtlicher Computertypen im Verein vertreten sind - gerade diese Vielfalt macht
        eine der Besonderheiten des Vereines aus.

        Jeden "1. Donnerstag im Monat" treffen sich einige Mitglieder der RG600 hier zum Plausch sowie Essen und
        Trinken. In den Wintermonaten tun wir dies in der "Goldenen Gerste" in Frankfurt-Bonames.
    </description>
    <url>http://www.auge.de/auge-regional/rg-frankfurt</url>
    <tags>
        <tag>Apple</tag>
        <tag>Computer</tag>
    </tags>
    <contact>
        <hashtag>#hackffm</hashtag>
    </contact>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/pugffm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>palmusergroup frankfurt</name>
    <nickname>pugffm</nickname>
    <description>Seit März 2003 gibt es bereits die Palmusergroup Frankfurt. In dieser Zeit haben wir viele
        Stammteilnehmer, aber immer wieder auch Neulinge anziehen können. Hier können sich PDA /
        Smartphone-Interessierte (alle Betriebssysteme), Anfänger und Freaks austauschen, Spaß haben und nach
        Herzenslust fachsimpeln. Über "normale" Themen darf natürlich auch geredet werden. Mittlerweile wird auch
        ausgiebig über Navigation gefachsimpelt, sowohl mit dem PDA / Smartphone als auch mit Standalone Geräten.
    </description>
    <url>http://pugfrankfurt.blogspot.de/</url>
    <tags>
        <tag>Palm</tag>
        <tag>Mobile</tag>
        <tag>Smartphone</tag>
    </tags>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/skrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Softwerkskammer Rhein-Main</name>
    <nickname>SKRM</nickname>
    <description>Wir sind eine Community of Professionals, die Ã¼ber ganz Deutschland verteilt sind. Wir wollen die
        richtige Software entwickeln, und wir wollen die Software richtig entwickeln.
    </description>
    <url>http://www.softwerkskammer.de/wiki/SoftwerkskammerFfm</url>
    <tags>
        <tag>Software Craftsmanship</tag>
    </tags>
    <contact>
        <hashtag>#skrm</hashtag>
    </contact>
    <photocredits>
        <group>Foto: [Markus Tacker](http://tckr.cc/).</group>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/cassandra.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Cassandra Frankfurt</name>
    <description>The Apache Cassandra Project develops a highly scalable second-generation distributed database,
        bringing together Dynamo's fully distributed design and Bigtable's ColumnFamily-based data model. The Frankfurt
        Apache Cassandra User Group is a highly awesome meetup group, bringing together cool people distributed across
        Frankfurt to talk about our favorite NoSQL implementation, Apache Cassandra.
    </description>
    <url>http://www.meetup.com/Frankfurt-Cassandra-Users/</url>
    <tags>
        <tag>Cassandra</tag>
        <tag>NoSQL</tag>
        <tag>Big Data</tag>
    </tags>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/ffda.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Freifunk Darmstadt</name>
    <nickname>ffda</nickname>
    <description>Wir wollen in Darmstadt eine Ortsgruppe für Freifunk aufbauen. 
         Unser Ziel ist es, ein vermeschtes WLAN-Netz über große Bereiche von
         Darmstadt in Betrieb zu nehmen.
    </description>
    <url>http://freifunk-darmstadt.de</url>
    <tags>
        <tag>Freifunk</tag>
        <tag>Darmstadt</tag>
        <tag>WLAN</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>http://lists.freifunk.net/mailman/listinfo/darmstadt-freifunk.net</url>
            <label>Mailingliste</label>
            <description>Unsere Mailingliste für Diskussionen und aktuelle Informationen
            </description>
        </mailinglist>
        <twitter>@FreifunkDA</twitter>
        <hashtag>#FreifunkDA</hashtag>
    </contact>
    <schedule>
        <!-- Entweder ical-Feed angeben oder Meetings manuell eintragen -->
        <!-- ical> https://www.google.com/calendar/ical/q408a75de70rb2ebqka3i18nc0%40group.calendar.google.com/public/basic.ics
            </ical -->
        <meeting>
            <time>2014-02-11T19:30:00+01:00</time>
            <name>Erstes Treffen von Freifunk Darmstadt</name>
            <location>
                <name>Trollhöhle Chaos Darmstadt</name>
                <url>http://chaos-darmstadt.de</url>
                <publictransport>Straßenbahn Linien 5,6,7 und 8 Haltestelle Pallaswiesenstraße</publictransport>
                <street>Wilhem-Leuschner-Str. 36</street>
                <zip>64293</zip>
                <city>Darmstadt</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <logo>Offizilles [Freifunk-Logo](https://wiki.freifunk.net/Datei:175x170_freifunknet.png)</logo>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/cccmzwi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Chaos Computer Club Mainz / Wiesbaden</name>
    <nickname>CCCMZWI</nickname>
    <description>Unsere lockeren Treffen sind Basis für Projekte: Zusammen programmieren oder wilde Lötaktionen,
        organisieren von Veranstaltungen oder Diskussionsrunden, planen neuer Projekte, die neusten Memes bequatschen…
        alles das ist das Chaos. Durch diese Vielzahl von unterschiedlichen Aktivitäten trifft man immer wieder auf sehr
        interessante Leute bei uns. Bei uns ist jeder herzlich willkommen, auch wenn er sich nicht den ganzen Tag mit
        Computern auseinander setzt.
    </description>
    <url>http://www.cccmz.de/</url>
    <tags>
        <tag>CCC</tag>
        <tag>Chaos Computer Club Mainz</tag>
        <tag>Chaos Computer Club Wiesbaden</tag>
    </tags>
    <contact>
        <twitter>@cccmz</twitter>
        <hashtag>#cccmz</hashtag>
        <facebook>https://www.facebook.com/cccmz</facebook>
        <!--<irc>irc://irc.hackint.eu/%23cccmz</irc>-->
    </contact>
    <schedule>
        <ical>https://www.cccmz.de/feed/my-calendar-ics/</ical>
    </schedule>
    <photocredits>
        <logo>Vielen Dank an @miracula_de</logo>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/agilerheinmain.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Agile Rhein-Main</name>
    <description>Die "Agile Rhein-Main" ist ein regionales Netzwerk mit den Interessengebieten: Agil, Scrum, agiles
        Projektmanagement, agile Software-Entwicklung, Kanban, Lean Software Development, Agile Organisation etc.
    </description>
    <url>https://www.xing.com/net/pri4044d1x/agilerheinmain/</url>
    <tags>
        <tag>Agile</tag>
        <tag>Scrum</tag>
        <tag>Kanban</tag>
    </tags>
    <contact>
        <hashtag>#agileRM</hashtag>
    </contact>
    <schedule>
        <meeting>
            <time>2013-04-04T19:00:00+02:00</time>
            <name>Agile Vorgehensweisen und Methoden in der Konstruktion physischer Produkte</name>
            <url>https://www.xing.com/events/agile-vorgehensweisen-methoden-konstruktion-physischer-produkte-1215834
            </url>
            <location>
                <name>//SEIBERT/MEDIA GmbH</name>
                <street>Kirchgasse 6 / LuisenForum</street>
                <zip>65185</zip>
                <city>Wiesbaden</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-02-04T18:30:00+01:00</time>
            <name>The S.O.L.I.D. Principles of OO and Agile Design</name>
            <description>Robert "Uncle Bob" Martin spricht am 4.2. in Frankfurt über “The S.O.L.I.D. Principles of OO
                and Agile Design”
            </description>
            <url>
                https://www.xing.com/events/robert-uncle-bob-martin-spricht-4-2-frankfurt-the-principles-of-oo-and-agile-design-1183895
            </url>
        </meeting>
    </schedule>
    <photocredits>
        <group>Foto: [Paul Herwarth von
            Bittenfeld](https://www.facebook.com/photo.php?fbid=10152200783510400&amp;set=a.10152200782965400.1073741826.56023505399)
        </group>
    </photocredits>
</usergroup>
