=== BenjaminHerbert/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="usergroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="nonEmptyString">
                    <xs:annotation>
                        <xs:documentation>Vollständiger Name der Usergroup in Langfassung,
                            z.B. Python UserGroup RheinMain
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="nickname" type="nonEmptyString" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="description" type="nonEmptyString">
                    <xs:annotation>
                        <xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
                            ausführlich sein.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="url" type="xs:anyURI">
                    <xs:annotation>
                        <xs:documentation>Die URL der Homepage der Usergroup.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="tags">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tag" type="xs:token" maxOccurs="3"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mailinglist" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="url" type="xs:anyURI"/>
                                        <xs:element name="label" type="nonEmptyString"/>
                                        <xs:element name="description" type="nonEmptyString" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" minOccurs="0" type="email"/>
                            <xs:element name="twitter" minOccurs="0" type="twitter"/>
                            <xs:element name="hashtag" minOccurs="0" type="hashtag"/>
                            <xs:element name="facebook" minOccurs="0" type="facebook"/>
                            <xs:element name="googleplus" minOccurs="0" type="googleplus"/>
                            <xs:element name="xing" minOccurs="0" type="xing"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="defaultmeetinglocation" type="location" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Dieses Element beschreibt die den Ort, an dem sich die Usergroup normalerweise
                            trifft. Kann durch die Information einzelnen Meetings überschrieben werden. Bei iCal
                            überschreibt die defaultlocation immer die Angabe aus dem iCal-Feed.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="schedule" minOccurs="0">
                    <xs:complexType>
                        <xs:annotation>
                            <xs:documentation>Liefert Information zu den nächsten Treffen der
                                UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
                                werden, oder die Meetings werden manuell konfiguriert.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:choice>
                            <xs:element name="ical" type="xs:anyURI"/>
                            <xs:element name="meeting" maxOccurs="unbounded" type="meeting"/>
                        </xs:choice>
                        <xs:attribute name="usedefaultmeetinglocation" type="xs:boolean"
                                      default="false" use="optional">
                            <xs:annotation>
                                <xs:documentation>Gibt an, ob für die Ortsangabe die Angaben aus
                                    ../defaultmeetinglocation verwendet werden sollen (wenn
                                    vorhanden).
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sponsors" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sponsor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="nonEmptyString"/>
                                        <xs:element name="url" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="photocredits" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="logo" type="nonEmptyString" minOccurs="0"/>
                            <xs:element name="group" type="nonEmptyString" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="email">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für E-Mail Adressen
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="twitter">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Twitter-Handles
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="@[a-zA-Z0-9_]{1,15}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="hashtag">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Hashtags
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="#[a-zA-Z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="facebook">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf facebook.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.facebook\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="xing">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf xing.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.xing\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="googleplus">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf Google+
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://plus\.google\.com/.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nonEmptyString">
        <xs:annotation>
            <xs:documentation>Ein nicht-leerer String</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="meeting">
        <xs:annotation>
            <xs:documentation>Definiert einen Datentyp für Meetings (zukünftige
                und vergangene)
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="time" type="xs:dateTime"/>
            <xs:element name="name" type="nonEmptyString"/>
            <xs:element name="description" type="nonEmptyString" minOccurs="0"/>
            <xs:element name="url" type="xs:anyURI" minOccurs="0"/>
            <xs:element name="location" type="location" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="plz">
        <xs:annotation>
            <xs:documentation>Eine deutsche PLZ</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="10000"/>
            <xs:maxInclusive value="99999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="location">
        <xs:sequence>
            <xs:element name="name" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. OFfenraum Coworking Space
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. OFfenraum ist ein Coworking Space im
                        Rhein-Main-Gebiet südlich von Frankfurt in Offenbach am Main,
                        in der Nähe des Hauptbahnhofs, Hassia Fabrik und
                        Stadtkrankenhaus.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="url" type="xs:anyURI" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. http://offenraum.de/#lage
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="twitter" type="twitter" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. @OFfenraum
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="publictransport" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Regionalbahn HBf Offenbach. S1, S2, S8,
                        S9 Offenbach Markplatz. Bus 104 Haydnstraße.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="street" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. Senefelderstr. 63</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="zip" type="plz">
                <xs:annotation>
                    <xs:documentation>z.B. 63069</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="city" type="nonEmptyString">
                <xs:annotation>
                    <xs:documentation>z.B. Offenbach</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="region" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Hessen</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="country" type="nonEmptyString"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>z.B. Deutschland</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BenjaminHerbert/ugrm-data/usergroup/leanstartupcircle.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Lean Startup Circle Rhein-Main</name>
    <description>Der Lean Startup Circle Rhein-Main ist eine Gruppe Gleichgesinnter, die sich über die Ideen und
        Methoden des Lean Startup austauschen möchte. Lean Startup ist ein Vorgehen für die Realisierung von Produkten
        und Dienstleistungen unter Unsicherheit, das sich zunehmender Beliebtheit erfreut.
    </description>
    <url>https://www.xing.com/net/prib45109x/leanstartuprm</url>
    <tags>
        <tag>Lean Startup</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2013-09-11T19:00:00+02:00</time>
            <name>Lean Startup Circle: "Life’s too short to build something nobody wants." - Ash Maurya</name>
            <description>Mit Blick auf den Running Lean Workshop von Ash Maurya in Frankfurt wollen wir uns (noch einmal) näher mit seinen Methoden und Werkzeugen befassen: Lean Canvas, Lean Stack, 3 principles of running lean. Idealerweise sind wir im Anschluss alle so up-to-date in den Basics der Methodik, dass wir in seinem Workshop am 23/24.9. ein offenes Ohr für seine Beispiele, Lessons und Schlussfolgerungen haben. Paul Herwarth und ich werden etwas vorstellen. Bringt eure Ergänzungen und Fragen gern mit. Wenn es klappt, schalten wir Ash kurz zur Beantwortung von Fragen dazu.</description>
            <url>https://www.xing.com/events/lean-startup-circle-life-too-short-to-build-something-nobody-wants-ash-maurya-1282045</url>
            <location>
                <name>StartFFM Coworking Space</name>
                <url>http://www.start-ffm.de/</url>
                <publictransport>U-Bahn U6, Bus 34, N1, N11, N2, 34, N1, N11, N2</publictransport>
                <street>Seelenberger Str. 2</street>
                <zip>60489</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-02-25T18:30:00+01:00</time>
            <name>6. Treffen des Lean Startup Circle Rhein-Main in Wiesbaden</name>
            <url>https://www.xing.com/events/6-treffen-lean-startup-circle-rhein-main-wiesbaden-1191900</url>
            <location>
                <name>heimathafen Wiesbaden</name>
                <description>
                    Unsere Vision ist es, eine Plattform zu schaffen. Eine Plattform für Kreative &amp; Wissensarbeiter,
                    für Freiberufler &amp; Startups, für Selbstständige und Agenturen in Wiesbaden.
                </description>
                <url>http://heimathafen-wiesbaden.de/</url>
                <twitter>@heimathafenWI</twitter>
                <publictransport>Mit den Buslinien 3, 6, 16, 28, 33, 36, 60, 67 zur Haltestelle Adelheidstraße (2
                    Minuten Fußweg)
                </publictransport>
                <street>Karlstraße 22</street>
                <zip>65185</zip>
                <city>Wiesbaden</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <group>Foto: [Paul Herwarth von
            Bittenfeld](http://www.flickr.com/photos/pherwarth/7179080251/in/set-72157630046900577/)
        </group>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/ruby.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           incubator="true">
    <name>Ruby-Usergroup Rhein-Main</name>
    <description>Max möchte eine Ruby-Usergroup im RheinMain-Gebiet gründen.</description>
    <url>http://usergroups.rheinmainrocks.de/~ruby</url>
    <tags>
        <tag>Ruby</tag>
        <tag>Rails</tag>
    </tags>
    <contact>
        <team>
            <person>
                <name>Max Trense</name>
                <url>http://www.namics.com/menschen/mitarbeiter/uebersicht/zeige/max-trense/</url>
                <email>max.trense@namics.com</email>
            </person>
        </team>
    </contact>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/hadoop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" incubator="true">
    <name>Hadoop UG RheinMain</name>
    <description>Uwe möchte eine Hadoop Usergroup im RheinMain-Gebiet gründen.</description>
    <url>http://usergroups.rheinmainrocks.de/~hadoop</url>
    <tags>
        <tag>Hadoop</tag>
        <tag>Cloud</tag>
    </tags>
    <contact>
        <team>
            <person>
                <name>Uwe Seiler</name>
                <url>https://www.xing.com/profile/Uwe_Seiler</url>
                <email>uwe.seiler@codecentric.de</email>
            </person>
        </team>
    </contact>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/openstack.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>OpenStack MeetUp Frankfurt</name>
    <description>Thinking about an OpenStack and Open Source Way to Cloud this Group should bring together anyone
        interested in the topic from all different sides. We are looking for Open Source Enthusiasts but also people who
        are new to the Open Approach.
    </description>
    <url>http://www.meetup.com/OpenStack-MeetUp-Frankfurt/</url>
    <tags>
        <tag>OpenStack</tag>
        <tag>Cloud</tag>
        <tag>Virtualization</tag>
    </tags>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/phpugffm.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
	<name>PHP Usergroup Frankfurt am Main</name>
	<nickname>PHPUGFFM</nickname>
	<description>
		Alle zwei Monate trifft sich die PHPUGFFM
		in verschiedenen Locations um über Tipps und Neuigkeiten der
		weitverbreiteten Serverscriptsprache zu diskutieren.
		Auch Programmierer aus anderen Bereichen sind herzlich willkommen!
	</description>
	<url>http://phpugffm.de</url>
    <tags>
        <tag>PHP</tag>
    </tags>
	<contact>
		<mailinglist>
			<url>https://groups.google.com/forum/#!forum/phpugffm</url>
			<label>Mailingliste</label>
			<description>zum Austausch von Mitgliedern und Interessierten
			</description>
		</mailinglist>
		<twitter>@phpugffm</twitter>
		<hashtag>#phpugffm</hashtag>
	</contact>
	<schedule>
		<!-- Entweder ical-Feed angeben oder Meetings manuell eintragen -->
		<!-- ical> https://www.google.com/calendar/ical/q408a75de70rb2ebqka3i18nc0%40group.calendar.google.com/public/basic.ics 
			</ical -->
		<meeting>
			<time>2013-03-21T19:00:00+01:00</time>
			<name>PHPUGFFM II / 2013</name>
			<url>http://www.phpugffm.de/?event=phpugffm-ii-2013</url>
		</meeting>
		<meeting>
			<time>2013-05-23T19:00:00+01:00</time>
			<name>PHPUGFFM III / 2013</name>
			<url>http://www.phpugffm.de/?event=phpugffm-iii-2013</url>
		</meeting>
		<meeting>
			<time>2013-08-31T19:00:00+01:00</time>
			<name>PHP BBQ 2013</name>
			<url>http://www.phpugffm.de/?event=phpugffm-iii-iv-2013-php-bbq</url>
		</meeting>
		<meeting>
			<time>2013-09-19T19:00:00+01:00</time>
			<name>PHPUGFFM IV / 2013</name>
			<url>http://www.phpugffm.de/?event=phpugffm-iv-2013</url>
		</meeting>
		<meeting>
			<time>2013-11-21T19:00:00+01:00</time>
			<name>PHPUGFFM V / 2013</name>
			<url>http://www.phpugffm.de/?event=phpugffm-v-2013</url>
		</meeting>
	</schedule>
	<sponsors>
		<sponsor>
			<name>O'Reilly Verlag</name>
			<url>http://www.oreilly.de</url>
		</sponsor>
		<sponsor>
			<name>Jetbrains</name>
			<url>http://jetbrains.com/</url>
		</sponsor>
		<sponsor>
			<name>Brot und Spiele GmbH</name>
			<url>http://spieletipps.de/</url>
		</sponsor>
		<sponsor>
			<name>dmr solutions gmbh</name>
			<url>http://www.dmr-solutions.com/</url>
		</sponsor>
	</sponsors>
    <photocredits>
        <logo>Das Logo ist eine Eigenkreation mehrerer Schöpfer, u.A. Tamara Bryun und Christian Nielebock.</logo>
        <group>Foto: Markus Tacker.</group>
    </photocredits>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/girm.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Regionalgruppe RheinMain der Gesellschaft für Informatik e.V.</name>
    <nickname>GIRM</nickname>
    <description markdown="true">Die GI-Rhein-Main ist ein Treffpunkt für Informatiker und IT-Experten im
        Rhein-Main-Gebiet.

        Die GI-Rhein-Main ist eine Regionalgruppe der [Gesellschaft für Informatik](http://www.gi.de/), der [IEEE
        Computer Society](http://www.computer.org/) und des
        [German Chapter of the ACM](http://www.informatik.org/), der deutschen Abteilung der [Association of Computing
        Machinery](http://www.acm.org/).

        Die GI-Rhein-Main organisiert seit 1989 Veranstaltungen zu aktuellen Themen der Informatik. Die Veranstaltungen
        sind öffentlich, eine Mitgliedschaft ist nicht erforderlich.

        Wichtig ist dabei die praktische Anwendung der Gedankenaustausch. Was bringt das? Welche Erfahrungen und
        Anforderungen sind in der Praxis relevant?

        Wir haben ein breites Spektrum an Themen aus der Praxis und den Hochschulen. Zu den Veranstaltungen kommen
        erfahrungsgemäß etwa 20 bis 100 Teilnehmer. Der größte Teil der Teilnehmer kommt aus der EDV-Anwendung (Banken,
        Versicherungen usw.) und der EDV-Branche (z.B. Software AG, IBM, SAP, Telekom, ...), ein kleinerer Teil von den
        Hochschulen und Instituten der Region (z.B. TU Darmstadt, Uni Frankfurt, Fraunhofer).

        Der Arbeitskreis Freiberufler und Selbständige in der Regionalgruppe trifft sich ebenfalls regelmäßig. Wer einen
        Freiberufler sucht oder selbst als Freiberufler tätig ist, ist dort richtig.

        Die Regionalgruppe Rhein-Main ist unbürokratisch organisiert. Das Organisationsteam ist offen für Anregungen,
        Kritik und neue Ideen. Wollen Sie die Regionalgruppe aktiv mitgestalten? Sie sind herzlich willkommen. Bitte
        nehmen Sie Kontakt mit uns auf.
    </description>
    <url>http://www.gi-rhein-main.de/</url>
    <tags>
        <tag>Informatik</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2014-01-30T18:00:00+01:00</time>
            <name>Apps überall: welche Auswirkungen hat das auf bestehende Kernanwendungen?</name>
            <description>mit Impulsvorträgen von

                * Susanne Braun (Fraunhofer IGD)
                * Dr. Marion Kremer (Capgemini)
                * Claudia Ristow (Deutsche Lufthansa)

                Heute werden bereits mehr mobile Endgeräte verkauft als stationäre PCs, sehr viele Menschen in
                Deutschland haben ein Smartphone. Kinder und Jugendliche wachsen wie selbstverständlich damit auf.
                Gleichzeitig haben fast alle großen Unternehmen und Behörden bestehende Anwendungen, die als Host- oder
                Client-Server-Anwendungen gebaut wurden und die jetzt in diese neue smarte Welt integriert werden sollen
                und müssen. Im Rahmen dieser Veranstaltung werden wir zunächst in drei Impulsvorträgen unterschiedliche
                Facetten des Themas beleuchten und freuen uns dann auf eine intensive Diskussion mit Ihnen.

                Der Vortrag richtet sich an alle Interessierten aus Wirtschaft, öffentlicher Verwaltung und
                Wissenschaft, die sehen möchten, wie die Welt der Apps auch die Bereiche der IT verändern wird, die
                zunächst gar nicht betroffen wirken.

                Die Teilnahme ist kostenlos. Im Anschluss an den Vortrag lädt das IGD zu einem Get-Together ein.
            </description>
            <url>
                http://www.eventbrite.de/e/apps-uberall-welche-auswirkungen-hat-das-auf-bestehende-kernanwendungen-tickets-9879634252
            </url>
            <location>
                <name>Fraunhofer Institute for Computer Graphics Research IGD</name>
                <url>https://www.igd.fraunhofer.de/</url>
                <street>Fraunhoferstr. 5</street>
                <zip>64283</zip>
                <city>Darmstadt</city>
            </location>
        </meeting>
    </schedule>
    <team>
        <person>
            <name>Dr. Joachim Rix</name>
            <email>joachim.rix@igd.fraunhofer.de</email>
        </person>
    </team>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/sem.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>SEM-Stammtisch-Frankfurt</name>
    <description>Ein Stammtisch f√ºr alle SEO Themen im Rhein-Main-Gebiet. Der Standort wechselt immer mal wieder und ist
        mal in Aschaffenburg oder auch in Darmstadt.
    </description>
    <url>http://www.sem-stammtisch-frankfurt.de/</url>
    <tags>
        <tag>SEM</tag>
        <tag>SEO</tag>
        <tag>SEA</tag>
    </tags>
</usergroup>

=== BenjaminHerbert/ugrm-data/usergroup/tex.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Frankfurter TeX-Stammtisch</name>
    <nickname>TeXStammtisch</nickname>
    <description>Austausch zu TeX/LaTeX in Frankfurt.
    </description>
    <url>http://www.lug-frankfurt.de/TeXStammtisch</url>
    <tags>
        <tag>Latex</tag>
        <tag>Tex</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>https://wiki.lugfrankfurt.de/mailman/listinfo/tex</url>
            <label>Mailingliste</label>
        </mailinglist>
    </contact>
</usergroup>
